INSERT INTO public.vertices (id, parent_id) VALUES (3, null);
INSERT INTO public.vertices (id, parent_id) VALUES (2, 3);
INSERT INTO public.vertices (id, parent_id) VALUES (4, 3);
INSERT INTO public.vertices (id, parent_id) VALUES (1, 2);
INSERT INTO public.vertices (id, parent_id) VALUES (5, 4);
INSERT INTO public.vertices (id, parent_id) VALUES (7, 4);
INSERT INTO public.vertices (id, parent_id) VALUES (6, 2);
INSERT INTO public.vertices (id, parent_id) VALUES (9, 6);
INSERT INTO public.vertices (id, parent_id) VALUES (8, 6);
